# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/henry/chewing-local

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/henry/chewing-local

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/henry/chewing-local/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henry/chewing-local/CMakeFiles /home/henry/chewing-local/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henry/chewing-local/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named chewing-editor

# Build rule for target.
chewing-editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chewing-editor
.PHONY : chewing-editor

# fast build rule for target.
chewing-editor/fast:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/build
.PHONY : chewing-editor/fast

#=============================================================================
# Target rules for targets named chewing-editor_automoc

# Build rule for target.
chewing-editor_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chewing-editor_automoc
.PHONY : chewing-editor_automoc

# fast build rule for target.
chewing-editor_automoc/fast:
	$(MAKE) -f CMakeFiles/chewing-editor_automoc.dir/build.make CMakeFiles/chewing-editor_automoc.dir/build
.PHONY : chewing-editor_automoc/fast

#=============================================================================
# Target rules for targets named en_US-ts

# Build rule for target.
en_US-ts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 en_US-ts
.PHONY : en_US-ts

# fast build rule for target.
en_US-ts/fast:
	$(MAKE) -f CMakeFiles/en_US-ts.dir/build.make CMakeFiles/en_US-ts.dir/build
.PHONY : en_US-ts/fast

#=============================================================================
# Target rules for targets named exporter

# Build rule for target.
exporter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exporter
.PHONY : exporter

# fast build rule for target.
exporter/fast:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/build
.PHONY : exporter/fast

#=============================================================================
# Target rules for targets named exporter_automoc

# Build rule for target.
exporter_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exporter_automoc
.PHONY : exporter_automoc

# fast build rule for target.
exporter_automoc/fast:
	$(MAKE) -f CMakeFiles/exporter_automoc.dir/build.make CMakeFiles/exporter_automoc.dir/build
.PHONY : exporter_automoc/fast

#=============================================================================
# Target rules for targets named importer

# Build rule for target.
importer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 importer
.PHONY : importer

# fast build rule for target.
importer/fast:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/build
.PHONY : importer/fast

#=============================================================================
# Target rules for targets named importer_automoc

# Build rule for target.
importer_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 importer_automoc
.PHONY : importer_automoc

# fast build rule for target.
importer_automoc/fast:
	$(MAKE) -f CMakeFiles/importer_automoc.dir/build.make CMakeFiles/importer_automoc.dir/build
.PHONY : importer_automoc/fast

#=============================================================================
# Target rules for targets named lrelease

# Build rule for target.
lrelease: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lrelease
.PHONY : lrelease

# fast build rule for target.
lrelease/fast:
	$(MAKE) -f CMakeFiles/lrelease.dir/build.make CMakeFiles/lrelease.dir/build
.PHONY : lrelease/fast

#=============================================================================
# Target rules for targets named lupdate

# Build rule for target.
lupdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lupdate
.PHONY : lupdate

# fast build rule for target.
lupdate/fast:
	$(MAKE) -f CMakeFiles/lupdate.dir/build.make CMakeFiles/lupdate.dir/build
.PHONY : lupdate/fast

#=============================================================================
# Target rules for targets named prepare_lrelease

# Build rule for target.
prepare_lrelease: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prepare_lrelease
.PHONY : prepare_lrelease

# fast build rule for target.
prepare_lrelease/fast:
	$(MAKE) -f CMakeFiles/prepare_lrelease.dir/build.make CMakeFiles/prepare_lrelease.dir/build
.PHONY : prepare_lrelease/fast

#=============================================================================
# Target rules for targets named prepare_lupdate

# Build rule for target.
prepare_lupdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prepare_lupdate
.PHONY : prepare_lupdate

# fast build rule for target.
prepare_lupdate/fast:
	$(MAKE) -f CMakeFiles/prepare_lupdate.dir/build.make CMakeFiles/prepare_lupdate.dir/build
.PHONY : prepare_lupdate/fast

#=============================================================================
# Target rules for targets named run-test

# Build rule for target.
run-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-test
.PHONY : run-test

# fast build rule for target.
run-test/fast:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/build
.PHONY : run-test/fast

#=============================================================================
# Target rules for targets named run-test_automoc

# Build rule for target.
run-test_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-test_automoc
.PHONY : run-test_automoc

# fast build rule for target.
run-test_automoc/fast:
	$(MAKE) -f CMakeFiles/run-test_automoc.dir/build.make CMakeFiles/run-test_automoc.dir/build
.PHONY : run-test_automoc/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named util_automoc

# Build rule for target.
util_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_automoc
.PHONY : util_automoc

# fast build rule for target.
util_automoc/fast:
	$(MAKE) -f CMakeFiles/util_automoc.dir/build.make CMakeFiles/util_automoc.dir/build
.PHONY : util_automoc/fast

#=============================================================================
# Target rules for targets named zh_TW-ts

# Build rule for target.
zh_TW-ts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zh_TW-ts
.PHONY : zh_TW-ts

# fast build rule for target.
zh_TW-ts/fast:
	$(MAKE) -f CMakeFiles/zh_TW-ts.dir/build.make CMakeFiles/zh_TW-ts.dir/build
.PHONY : zh_TW-ts/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f gmock/CMakeFiles/gmock.dir/build.make gmock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_automoc

# Build rule for target.
gmock_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_automoc
.PHONY : gmock_automoc

# fast build rule for target.
gmock_automoc/fast:
	$(MAKE) -f gmock/CMakeFiles/gmock_automoc.dir/build.make gmock/CMakeFiles/gmock_automoc.dir/build
.PHONY : gmock_automoc/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f gmock/CMakeFiles/gmock_main.dir/build.make gmock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock_main_automoc

# Build rule for target.
gmock_main_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main_automoc
.PHONY : gmock_main_automoc

# fast build rule for target.
gmock_main_automoc/fast:
	$(MAKE) -f gmock/CMakeFiles/gmock_main_automoc.dir/build.make gmock/CMakeFiles/gmock_main_automoc.dir/build
.PHONY : gmock_main_automoc/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gmock/gtest/CMakeFiles/gtest.dir/build.make gmock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_automoc

# Build rule for target.
gtest_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_automoc
.PHONY : gtest_automoc

# fast build rule for target.
gtest_automoc/fast:
	$(MAKE) -f gmock/gtest/CMakeFiles/gtest_automoc.dir/build.make gmock/gtest/CMakeFiles/gtest_automoc.dir/build
.PHONY : gtest_automoc/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gmock/gtest/CMakeFiles/gtest_main.dir/build.make gmock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest_main_automoc

# Build rule for target.
gtest_main_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main_automoc
.PHONY : gtest_main_automoc

# fast build rule for target.
gtest_main_automoc/fast:
	$(MAKE) -f gmock/gtest/CMakeFiles/gtest_main_automoc.dir/build.make gmock/gtest/CMakeFiles/gtest_main_automoc.dir/build
.PHONY : gtest_main_automoc/fast

chewing-editor_automoc.o: chewing-editor_automoc.cpp.o
.PHONY : chewing-editor_automoc.o

# target to build an object file
chewing-editor_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/chewing-editor_automoc.cpp.o
.PHONY : chewing-editor_automoc.cpp.o

chewing-editor_automoc.i: chewing-editor_automoc.cpp.i
.PHONY : chewing-editor_automoc.i

# target to preprocess a source file
chewing-editor_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/chewing-editor_automoc.cpp.i
.PHONY : chewing-editor_automoc.cpp.i

chewing-editor_automoc.s: chewing-editor_automoc.cpp.s
.PHONY : chewing-editor_automoc.s

# target to generate assembly for a file
chewing-editor_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/chewing-editor_automoc.cpp.s
.PHONY : chewing-editor_automoc.cpp.s

exporter_automoc.o: exporter_automoc.cpp.o
.PHONY : exporter_automoc.o

# target to build an object file
exporter_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/exporter_automoc.cpp.o
.PHONY : exporter_automoc.cpp.o

exporter_automoc.i: exporter_automoc.cpp.i
.PHONY : exporter_automoc.i

# target to preprocess a source file
exporter_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/exporter_automoc.cpp.i
.PHONY : exporter_automoc.cpp.i

exporter_automoc.s: exporter_automoc.cpp.s
.PHONY : exporter_automoc.s

# target to generate assembly for a file
exporter_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/exporter_automoc.cpp.s
.PHONY : exporter_automoc.cpp.s

importer_automoc.o: importer_automoc.cpp.o
.PHONY : importer_automoc.o

# target to build an object file
importer_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/importer_automoc.cpp.o
.PHONY : importer_automoc.cpp.o

importer_automoc.i: importer_automoc.cpp.i
.PHONY : importer_automoc.i

# target to preprocess a source file
importer_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/importer_automoc.cpp.i
.PHONY : importer_automoc.cpp.i

importer_automoc.s: importer_automoc.cpp.s
.PHONY : importer_automoc.s

# target to generate assembly for a file
importer_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/importer_automoc.cpp.s
.PHONY : importer_automoc.cpp.s

qrc_ts.o: qrc_ts.cpp.o
.PHONY : qrc_ts.o

# target to build an object file
qrc_ts.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/qrc_ts.cpp.o
.PHONY : qrc_ts.cpp.o

qrc_ts.i: qrc_ts.cpp.i
.PHONY : qrc_ts.i

# target to preprocess a source file
qrc_ts.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/qrc_ts.cpp.i
.PHONY : qrc_ts.cpp.i

qrc_ts.s: qrc_ts.cpp.s
.PHONY : qrc_ts.s

# target to generate assembly for a file
qrc_ts.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/qrc_ts.cpp.s
.PHONY : qrc_ts.cpp.s

run-test_automoc.o: run-test_automoc.cpp.o
.PHONY : run-test_automoc.o

# target to build an object file
run-test_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/run-test_automoc.cpp.o
.PHONY : run-test_automoc.cpp.o

run-test_automoc.i: run-test_automoc.cpp.i
.PHONY : run-test_automoc.i

# target to preprocess a source file
run-test_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/run-test_automoc.cpp.i
.PHONY : run-test_automoc.cpp.i

run-test_automoc.s: run-test_automoc.cpp.s
.PHONY : run-test_automoc.s

# target to generate assembly for a file
run-test_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/run-test_automoc.cpp.s
.PHONY : run-test_automoc.cpp.s

src/exporter/ChewingExporter.o: src/exporter/ChewingExporter.cpp.o
.PHONY : src/exporter/ChewingExporter.o

# target to build an object file
src/exporter/ChewingExporter.cpp.o:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/src/exporter/ChewingExporter.cpp.o
.PHONY : src/exporter/ChewingExporter.cpp.o

src/exporter/ChewingExporter.i: src/exporter/ChewingExporter.cpp.i
.PHONY : src/exporter/ChewingExporter.i

# target to preprocess a source file
src/exporter/ChewingExporter.cpp.i:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/src/exporter/ChewingExporter.cpp.i
.PHONY : src/exporter/ChewingExporter.cpp.i

src/exporter/ChewingExporter.s: src/exporter/ChewingExporter.cpp.s
.PHONY : src/exporter/ChewingExporter.s

# target to generate assembly for a file
src/exporter/ChewingExporter.cpp.s:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/src/exporter/ChewingExporter.cpp.s
.PHONY : src/exporter/ChewingExporter.cpp.s

src/exporter/UserphraseExporter.o: src/exporter/UserphraseExporter.cpp.o
.PHONY : src/exporter/UserphraseExporter.o

# target to build an object file
src/exporter/UserphraseExporter.cpp.o:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/src/exporter/UserphraseExporter.cpp.o
.PHONY : src/exporter/UserphraseExporter.cpp.o

src/exporter/UserphraseExporter.i: src/exporter/UserphraseExporter.cpp.i
.PHONY : src/exporter/UserphraseExporter.i

# target to preprocess a source file
src/exporter/UserphraseExporter.cpp.i:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/src/exporter/UserphraseExporter.cpp.i
.PHONY : src/exporter/UserphraseExporter.cpp.i

src/exporter/UserphraseExporter.s: src/exporter/UserphraseExporter.cpp.s
.PHONY : src/exporter/UserphraseExporter.s

# target to generate assembly for a file
src/exporter/UserphraseExporter.cpp.s:
	$(MAKE) -f CMakeFiles/exporter.dir/build.make CMakeFiles/exporter.dir/src/exporter/UserphraseExporter.cpp.s
.PHONY : src/exporter/UserphraseExporter.cpp.s

src/importer/ChewingImporter.o: src/importer/ChewingImporter.cpp.o
.PHONY : src/importer/ChewingImporter.o

# target to build an object file
src/importer/ChewingImporter.cpp.o:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/ChewingImporter.cpp.o
.PHONY : src/importer/ChewingImporter.cpp.o

src/importer/ChewingImporter.i: src/importer/ChewingImporter.cpp.i
.PHONY : src/importer/ChewingImporter.i

# target to preprocess a source file
src/importer/ChewingImporter.cpp.i:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/ChewingImporter.cpp.i
.PHONY : src/importer/ChewingImporter.cpp.i

src/importer/ChewingImporter.s: src/importer/ChewingImporter.cpp.s
.PHONY : src/importer/ChewingImporter.s

# target to generate assembly for a file
src/importer/ChewingImporter.cpp.s:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/ChewingImporter.cpp.s
.PHONY : src/importer/ChewingImporter.cpp.s

src/importer/HashImporter.o: src/importer/HashImporter.cpp.o
.PHONY : src/importer/HashImporter.o

# target to build an object file
src/importer/HashImporter.cpp.o:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/HashImporter.cpp.o
.PHONY : src/importer/HashImporter.cpp.o

src/importer/HashImporter.i: src/importer/HashImporter.cpp.i
.PHONY : src/importer/HashImporter.i

# target to preprocess a source file
src/importer/HashImporter.cpp.i:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/HashImporter.cpp.i
.PHONY : src/importer/HashImporter.cpp.i

src/importer/HashImporter.s: src/importer/HashImporter.cpp.s
.PHONY : src/importer/HashImporter.s

# target to generate assembly for a file
src/importer/HashImporter.cpp.s:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/HashImporter.cpp.s
.PHONY : src/importer/HashImporter.cpp.s

src/importer/UserphraseImporter.o: src/importer/UserphraseImporter.cpp.o
.PHONY : src/importer/UserphraseImporter.o

# target to build an object file
src/importer/UserphraseImporter.cpp.o:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/UserphraseImporter.cpp.o
.PHONY : src/importer/UserphraseImporter.cpp.o

src/importer/UserphraseImporter.i: src/importer/UserphraseImporter.cpp.i
.PHONY : src/importer/UserphraseImporter.i

# target to preprocess a source file
src/importer/UserphraseImporter.cpp.i:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/UserphraseImporter.cpp.i
.PHONY : src/importer/UserphraseImporter.cpp.i

src/importer/UserphraseImporter.s: src/importer/UserphraseImporter.cpp.s
.PHONY : src/importer/UserphraseImporter.s

# target to generate assembly for a file
src/importer/UserphraseImporter.cpp.s:
	$(MAKE) -f CMakeFiles/importer.dir/build.make CMakeFiles/importer.dir/src/importer/UserphraseImporter.cpp.s
.PHONY : src/importer/UserphraseImporter.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/UserphraseModel.o: src/model/UserphraseModel.cpp.o
.PHONY : src/model/UserphraseModel.o

# target to build an object file
src/model/UserphraseModel.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/model/UserphraseModel.cpp.o
.PHONY : src/model/UserphraseModel.cpp.o

src/model/UserphraseModel.i: src/model/UserphraseModel.cpp.i
.PHONY : src/model/UserphraseModel.i

# target to preprocess a source file
src/model/UserphraseModel.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/model/UserphraseModel.cpp.i
.PHONY : src/model/UserphraseModel.cpp.i

src/model/UserphraseModel.s: src/model/UserphraseModel.cpp.s
.PHONY : src/model/UserphraseModel.s

# target to generate assembly for a file
src/model/UserphraseModel.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/model/UserphraseModel.cpp.s
.PHONY : src/model/UserphraseModel.cpp.s

src/model/UserphraseSortFilterProxyModel.o: src/model/UserphraseSortFilterProxyModel.cpp.o
.PHONY : src/model/UserphraseSortFilterProxyModel.o

# target to build an object file
src/model/UserphraseSortFilterProxyModel.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/model/UserphraseSortFilterProxyModel.cpp.o
.PHONY : src/model/UserphraseSortFilterProxyModel.cpp.o

src/model/UserphraseSortFilterProxyModel.i: src/model/UserphraseSortFilterProxyModel.cpp.i
.PHONY : src/model/UserphraseSortFilterProxyModel.i

# target to preprocess a source file
src/model/UserphraseSortFilterProxyModel.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/model/UserphraseSortFilterProxyModel.cpp.i
.PHONY : src/model/UserphraseSortFilterProxyModel.cpp.i

src/model/UserphraseSortFilterProxyModel.s: src/model/UserphraseSortFilterProxyModel.cpp.s
.PHONY : src/model/UserphraseSortFilterProxyModel.s

# target to generate assembly for a file
src/model/UserphraseSortFilterProxyModel.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/model/UserphraseSortFilterProxyModel.cpp.s
.PHONY : src/model/UserphraseSortFilterProxyModel.cpp.s

src/util/Userphrase.o: src/util/Userphrase.cpp.o
.PHONY : src/util/Userphrase.o

# target to build an object file
src/util/Userphrase.cpp.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/Userphrase.cpp.o
.PHONY : src/util/Userphrase.cpp.o

src/util/Userphrase.i: src/util/Userphrase.cpp.i
.PHONY : src/util/Userphrase.i

# target to preprocess a source file
src/util/Userphrase.cpp.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/Userphrase.cpp.i
.PHONY : src/util/Userphrase.cpp.i

src/util/Userphrase.s: src/util/Userphrase.cpp.s
.PHONY : src/util/Userphrase.s

# target to generate assembly for a file
src/util/Userphrase.cpp.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/Userphrase.cpp.s
.PHONY : src/util/Userphrase.cpp.s

src/util/UserphraseSet.o: src/util/UserphraseSet.cpp.o
.PHONY : src/util/UserphraseSet.o

# target to build an object file
src/util/UserphraseSet.cpp.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/UserphraseSet.cpp.o
.PHONY : src/util/UserphraseSet.cpp.o

src/util/UserphraseSet.i: src/util/UserphraseSet.cpp.i
.PHONY : src/util/UserphraseSet.i

# target to preprocess a source file
src/util/UserphraseSet.cpp.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/UserphraseSet.cpp.i
.PHONY : src/util/UserphraseSet.cpp.i

src/util/UserphraseSet.s: src/util/UserphraseSet.cpp.s
.PHONY : src/util/UserphraseSet.s

# target to generate assembly for a file
src/util/UserphraseSet.cpp.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/UserphraseSet.cpp.s
.PHONY : src/util/UserphraseSet.cpp.s

src/view/ChewingEditor.o: src/view/ChewingEditor.cpp.o
.PHONY : src/view/ChewingEditor.o

# target to build an object file
src/view/ChewingEditor.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/ChewingEditor.cpp.o
.PHONY : src/view/ChewingEditor.cpp.o

src/view/ChewingEditor.i: src/view/ChewingEditor.cpp.i
.PHONY : src/view/ChewingEditor.i

# target to preprocess a source file
src/view/ChewingEditor.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/ChewingEditor.cpp.i
.PHONY : src/view/ChewingEditor.cpp.i

src/view/ChewingEditor.s: src/view/ChewingEditor.cpp.s
.PHONY : src/view/ChewingEditor.s

# target to generate assembly for a file
src/view/ChewingEditor.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/ChewingEditor.cpp.s
.PHONY : src/view/ChewingEditor.cpp.s

src/view/Notification.o: src/view/Notification.cpp.o
.PHONY : src/view/Notification.o

# target to build an object file
src/view/Notification.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/Notification.cpp.o
.PHONY : src/view/Notification.cpp.o

src/view/Notification.i: src/view/Notification.cpp.i
.PHONY : src/view/Notification.i

# target to preprocess a source file
src/view/Notification.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/Notification.cpp.i
.PHONY : src/view/Notification.cpp.i

src/view/Notification.s: src/view/Notification.cpp.s
.PHONY : src/view/Notification.s

# target to generate assembly for a file
src/view/Notification.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/Notification.cpp.s
.PHONY : src/view/Notification.cpp.s

src/view/UserphraseDialog.o: src/view/UserphraseDialog.cpp.o
.PHONY : src/view/UserphraseDialog.o

# target to build an object file
src/view/UserphraseDialog.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseDialog.cpp.o
.PHONY : src/view/UserphraseDialog.cpp.o

src/view/UserphraseDialog.i: src/view/UserphraseDialog.cpp.i
.PHONY : src/view/UserphraseDialog.i

# target to preprocess a source file
src/view/UserphraseDialog.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseDialog.cpp.i
.PHONY : src/view/UserphraseDialog.cpp.i

src/view/UserphraseDialog.s: src/view/UserphraseDialog.cpp.s
.PHONY : src/view/UserphraseDialog.s

# target to generate assembly for a file
src/view/UserphraseDialog.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseDialog.cpp.s
.PHONY : src/view/UserphraseDialog.cpp.s

src/view/UserphraseView.o: src/view/UserphraseView.cpp.o
.PHONY : src/view/UserphraseView.o

# target to build an object file
src/view/UserphraseView.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseView.cpp.o
.PHONY : src/view/UserphraseView.cpp.o

src/view/UserphraseView.i: src/view/UserphraseView.cpp.i
.PHONY : src/view/UserphraseView.i

# target to preprocess a source file
src/view/UserphraseView.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseView.cpp.i
.PHONY : src/view/UserphraseView.cpp.i

src/view/UserphraseView.s: src/view/UserphraseView.cpp.s
.PHONY : src/view/UserphraseView.s

# target to generate assembly for a file
src/view/UserphraseView.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseView.cpp.s
.PHONY : src/view/UserphraseView.cpp.s

src/view/UserphraseViewMenu.o: src/view/UserphraseViewMenu.cpp.o
.PHONY : src/view/UserphraseViewMenu.o

# target to build an object file
src/view/UserphraseViewMenu.cpp.o:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseViewMenu.cpp.o
.PHONY : src/view/UserphraseViewMenu.cpp.o

src/view/UserphraseViewMenu.i: src/view/UserphraseViewMenu.cpp.i
.PHONY : src/view/UserphraseViewMenu.i

# target to preprocess a source file
src/view/UserphraseViewMenu.cpp.i:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseViewMenu.cpp.i
.PHONY : src/view/UserphraseViewMenu.cpp.i

src/view/UserphraseViewMenu.s: src/view/UserphraseViewMenu.cpp.s
.PHONY : src/view/UserphraseViewMenu.s

# target to generate assembly for a file
src/view/UserphraseViewMenu.cpp.s:
	$(MAKE) -f CMakeFiles/chewing-editor.dir/build.make CMakeFiles/chewing-editor.dir/src/view/UserphraseViewMenu.cpp.s
.PHONY : src/view/UserphraseViewMenu.cpp.s

test/testChewingExporter.o: test/testChewingExporter.cpp.o
.PHONY : test/testChewingExporter.o

# target to build an object file
test/testChewingExporter.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testChewingExporter.cpp.o
.PHONY : test/testChewingExporter.cpp.o

test/testChewingExporter.i: test/testChewingExporter.cpp.i
.PHONY : test/testChewingExporter.i

# target to preprocess a source file
test/testChewingExporter.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testChewingExporter.cpp.i
.PHONY : test/testChewingExporter.cpp.i

test/testChewingExporter.s: test/testChewingExporter.cpp.s
.PHONY : test/testChewingExporter.s

# target to generate assembly for a file
test/testChewingExporter.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testChewingExporter.cpp.s
.PHONY : test/testChewingExporter.cpp.s

test/testChewingImporter.o: test/testChewingImporter.cpp.o
.PHONY : test/testChewingImporter.o

# target to build an object file
test/testChewingImporter.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testChewingImporter.cpp.o
.PHONY : test/testChewingImporter.cpp.o

test/testChewingImporter.i: test/testChewingImporter.cpp.i
.PHONY : test/testChewingImporter.i

# target to preprocess a source file
test/testChewingImporter.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testChewingImporter.cpp.i
.PHONY : test/testChewingImporter.cpp.i

test/testChewingImporter.s: test/testChewingImporter.cpp.s
.PHONY : test/testChewingImporter.s

# target to generate assembly for a file
test/testChewingImporter.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testChewingImporter.cpp.s
.PHONY : test/testChewingImporter.cpp.s

test/testHashImporter.o: test/testHashImporter.cpp.o
.PHONY : test/testHashImporter.o

# target to build an object file
test/testHashImporter.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testHashImporter.cpp.o
.PHONY : test/testHashImporter.cpp.o

test/testHashImporter.i: test/testHashImporter.cpp.i
.PHONY : test/testHashImporter.i

# target to preprocess a source file
test/testHashImporter.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testHashImporter.cpp.i
.PHONY : test/testHashImporter.cpp.i

test/testHashImporter.s: test/testHashImporter.cpp.s
.PHONY : test/testHashImporter.s

# target to generate assembly for a file
test/testHashImporter.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testHashImporter.cpp.s
.PHONY : test/testHashImporter.cpp.s

test/testUserphraseImporter.o: test/testUserphraseImporter.cpp.o
.PHONY : test/testUserphraseImporter.o

# target to build an object file
test/testUserphraseImporter.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testUserphraseImporter.cpp.o
.PHONY : test/testUserphraseImporter.cpp.o

test/testUserphraseImporter.i: test/testUserphraseImporter.cpp.i
.PHONY : test/testUserphraseImporter.i

# target to preprocess a source file
test/testUserphraseImporter.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testUserphraseImporter.cpp.i
.PHONY : test/testUserphraseImporter.cpp.i

test/testUserphraseImporter.s: test/testUserphraseImporter.cpp.s
.PHONY : test/testUserphraseImporter.s

# target to generate assembly for a file
test/testUserphraseImporter.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testUserphraseImporter.cpp.s
.PHONY : test/testUserphraseImporter.cpp.s

test/testUserphraseSet.o: test/testUserphraseSet.cpp.o
.PHONY : test/testUserphraseSet.o

# target to build an object file
test/testUserphraseSet.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testUserphraseSet.cpp.o
.PHONY : test/testUserphraseSet.cpp.o

test/testUserphraseSet.i: test/testUserphraseSet.cpp.i
.PHONY : test/testUserphraseSet.i

# target to preprocess a source file
test/testUserphraseSet.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testUserphraseSet.cpp.i
.PHONY : test/testUserphraseSet.cpp.i

test/testUserphraseSet.s: test/testUserphraseSet.cpp.s
.PHONY : test/testUserphraseSet.s

# target to generate assembly for a file
test/testUserphraseSet.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testUserphraseSet.cpp.s
.PHONY : test/testUserphraseSet.cpp.s

test/testmain.o: test/testmain.cpp.o
.PHONY : test/testmain.o

# target to build an object file
test/testmain.cpp.o:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testmain.cpp.o
.PHONY : test/testmain.cpp.o

test/testmain.i: test/testmain.cpp.i
.PHONY : test/testmain.i

# target to preprocess a source file
test/testmain.cpp.i:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testmain.cpp.i
.PHONY : test/testmain.cpp.i

test/testmain.s: test/testmain.cpp.s
.PHONY : test/testmain.s

# target to generate assembly for a file
test/testmain.cpp.s:
	$(MAKE) -f CMakeFiles/run-test.dir/build.make CMakeFiles/run-test.dir/test/testmain.cpp.s
.PHONY : test/testmain.cpp.s

util_automoc.o: util_automoc.cpp.o
.PHONY : util_automoc.o

# target to build an object file
util_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/util_automoc.cpp.o
.PHONY : util_automoc.cpp.o

util_automoc.i: util_automoc.cpp.i
.PHONY : util_automoc.i

# target to preprocess a source file
util_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/util_automoc.cpp.i
.PHONY : util_automoc.cpp.i

util_automoc.s: util_automoc.cpp.s
.PHONY : util_automoc.s

# target to generate assembly for a file
util_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/util_automoc.cpp.s
.PHONY : util_automoc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... check"
	@echo "... chewing-editor"
	@echo "... chewing-editor_automoc"
	@echo "... edit_cache"
	@echo "... en_US-ts"
	@echo "... exporter"
	@echo "... exporter_automoc"
	@echo "... importer"
	@echo "... importer_automoc"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... lrelease"
	@echo "... lupdate"
	@echo "... package"
	@echo "... package_source"
	@echo "... prepare_lrelease"
	@echo "... prepare_lupdate"
	@echo "... rebuild_cache"
	@echo "... run-test"
	@echo "... run-test_automoc"
	@echo "... test"
	@echo "... util"
	@echo "... util_automoc"
	@echo "... zh_TW-ts"
	@echo "... gmock"
	@echo "... gmock_automoc"
	@echo "... gmock_main"
	@echo "... gmock_main_automoc"
	@echo "... gtest"
	@echo "... gtest_automoc"
	@echo "... gtest_main"
	@echo "... gtest_main_automoc"
	@echo "... chewing-editor_automoc.o"
	@echo "... chewing-editor_automoc.i"
	@echo "... chewing-editor_automoc.s"
	@echo "... exporter_automoc.o"
	@echo "... exporter_automoc.i"
	@echo "... exporter_automoc.s"
	@echo "... importer_automoc.o"
	@echo "... importer_automoc.i"
	@echo "... importer_automoc.s"
	@echo "... qrc_ts.o"
	@echo "... qrc_ts.i"
	@echo "... qrc_ts.s"
	@echo "... run-test_automoc.o"
	@echo "... run-test_automoc.i"
	@echo "... run-test_automoc.s"
	@echo "... src/exporter/ChewingExporter.o"
	@echo "... src/exporter/ChewingExporter.i"
	@echo "... src/exporter/ChewingExporter.s"
	@echo "... src/exporter/UserphraseExporter.o"
	@echo "... src/exporter/UserphraseExporter.i"
	@echo "... src/exporter/UserphraseExporter.s"
	@echo "... src/importer/ChewingImporter.o"
	@echo "... src/importer/ChewingImporter.i"
	@echo "... src/importer/ChewingImporter.s"
	@echo "... src/importer/HashImporter.o"
	@echo "... src/importer/HashImporter.i"
	@echo "... src/importer/HashImporter.s"
	@echo "... src/importer/UserphraseImporter.o"
	@echo "... src/importer/UserphraseImporter.i"
	@echo "... src/importer/UserphraseImporter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/UserphraseModel.o"
	@echo "... src/model/UserphraseModel.i"
	@echo "... src/model/UserphraseModel.s"
	@echo "... src/model/UserphraseSortFilterProxyModel.o"
	@echo "... src/model/UserphraseSortFilterProxyModel.i"
	@echo "... src/model/UserphraseSortFilterProxyModel.s"
	@echo "... src/util/Userphrase.o"
	@echo "... src/util/Userphrase.i"
	@echo "... src/util/Userphrase.s"
	@echo "... src/util/UserphraseSet.o"
	@echo "... src/util/UserphraseSet.i"
	@echo "... src/util/UserphraseSet.s"
	@echo "... src/view/ChewingEditor.o"
	@echo "... src/view/ChewingEditor.i"
	@echo "... src/view/ChewingEditor.s"
	@echo "... src/view/Notification.o"
	@echo "... src/view/Notification.i"
	@echo "... src/view/Notification.s"
	@echo "... src/view/UserphraseDialog.o"
	@echo "... src/view/UserphraseDialog.i"
	@echo "... src/view/UserphraseDialog.s"
	@echo "... src/view/UserphraseView.o"
	@echo "... src/view/UserphraseView.i"
	@echo "... src/view/UserphraseView.s"
	@echo "... src/view/UserphraseViewMenu.o"
	@echo "... src/view/UserphraseViewMenu.i"
	@echo "... src/view/UserphraseViewMenu.s"
	@echo "... test/testChewingExporter.o"
	@echo "... test/testChewingExporter.i"
	@echo "... test/testChewingExporter.s"
	@echo "... test/testChewingImporter.o"
	@echo "... test/testChewingImporter.i"
	@echo "... test/testChewingImporter.s"
	@echo "... test/testHashImporter.o"
	@echo "... test/testHashImporter.i"
	@echo "... test/testHashImporter.s"
	@echo "... test/testUserphraseImporter.o"
	@echo "... test/testUserphraseImporter.i"
	@echo "... test/testUserphraseImporter.s"
	@echo "... test/testUserphraseSet.o"
	@echo "... test/testUserphraseSet.i"
	@echo "... test/testUserphraseSet.s"
	@echo "... test/testmain.o"
	@echo "... test/testmain.i"
	@echo "... test/testmain.s"
	@echo "... util_automoc.o"
	@echo "... util_automoc.i"
	@echo "... util_automoc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

